# docker compose for development

version: "3.8"

services:
  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=mydocnote
      - POSTGRES_PASSWORD=0000
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  back:
    build: ./backend
    image: mydocnote_back:latest
    environment:
      - DATABASE_URL=postgresql://mydocnote:0000@postgres:5432/mydb?schema=public
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    command: >
      bash -c '
      yarn start'
    depends_on:
      - postgres
  front:
    build:
      context: ./frontend
      target: deps
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    command: "yarn start"
  prisma-studio:
    build: ./backend
    image: mydocnote_back:latest
    environment:
      - DATABASE_URL=postgresql://mydocnote:0000@postgres:5432/mydb?schema=public
    ports:
      - "5555:5555"
    volumes:
      - ./backend/prisma:/app/prisma:delegated
    command: "npx prisma studio"
    depends_on:
      - postgres
      - back
    
volumes:
  postgres:
